def MakePyTorchBatchNorm2D(node, raw_node, weights, rmodel):
    """
    Create a PyTorch-compatible BatchNorm2D operation using the SOFIE framework.

    Handles both affine=True (learnable scale/bias) and affine=False
    (constant scale=1, bias=0 generated by PyTorch as Constant nodes).

    Parameters:
    node (dict): parsed node info dict
    raw_node:    raw torch graph node
    weights:     model weights dict
    rmodel:      SOFIE RModel

    Returns:
    ROperator_BatchNormalization: A SOFIE operator for BatchNorm2D.
    """
    import numpy as np
    from ROOT.TMVA.Experimental import SOFIE

    fNodeDType  = node["nodeDType"][0]
    fInputs     = node["nodeInputs"]
    fOutputs    = node["nodeOutputs"]
    fAttributes = node["nodeAttributes"]

    if len(fInputs) != 5:
        raise RuntimeError(
            "TMVA::SOFIE BatchNorm2D expects 5 inputs but got {}".format(len(fInputs))
        )

    fNameX     = fInputs[0]
    fNameScale = fInputs[1]
    fNameBias  = fInputs[2]
    fNameMean  = fInputs[3]
    fNameVar   = fInputs[4]
    fNameY     = fOutputs[0]

    fEpsilon      = float(fAttributes.get("epsilon", 1e-5))
    fMomentum     = float(fAttributes.get("momentum", 0.9))
    fTrainingMode = int(fAttributes.get("training_mode", 0))

    # Get number of channels from running_mean shape
    if fNameMean in weights:
        num_features = weights[fNameMean].shape[0]
    else:
        num_features = 1

    # Handle affine=False: scale/bias are Constant nodes, not in weights dict
    # Register them manually as ones/zeros
    if fNameScale not in weights and not rmodel.IsInitializedTensor(fNameScale):
        scale_val = np.ones(num_features, dtype=np.float32)
        rmodel.AddInitializedTensor["float"](fNameScale, [num_features], scale_val)

    if fNameBias not in weights and not rmodel.IsInitializedTensor(fNameBias):
        bias_val = np.zeros(num_features, dtype=np.float32)
        rmodel.AddInitializedTensor["float"](fNameBias, [num_features], bias_val)

    if SOFIE.ConvertStringToType(fNodeDType) == SOFIE.ETensorType.FLOAT:
        op = SOFIE.ROperator_BatchNormalization["float"](
            fEpsilon, fMomentum, fTrainingMode,
            fNameX, fNameScale, fNameBias,
            fNameMean, fNameVar, fNameY
        )
        return op
    else:
        raise RuntimeError(
            "TMVA::SOFIE - Unsupported - BatchNorm2D does not support type " + fNodeDType
        )
