import os
import time
import tempfile

from .layers.elu import MakePyTorchELU
from .layers.maxpool2d import MakePyTorchMaxPool2D
from .layers.batchnorm2d import MakePyTorchBatchNorm2D
from .layers.rnn import MakePyTorchRNN
from .layers.lstm import MakePyTorchLSTM

def _node_get(node, key):
    """Helper to get node attribute without depending on onnx submodule."""
    sel = node.kindOf(key)
    return getattr(node, sel)(key)

def MakePyTorchGemm(node_data):
    """Parse Gemm (Linear layer) operator."""
    from ROOT.TMVA.Experimental import SOFIE
    attrs   = node_data["nodeAttributes"]
    inputs  = node_data["nodeInputs"]
    outputs = node_data["nodeOutputs"]
    dtype   = node_data["nodeDType"][0]

    nameA = inputs[0]
    nameB = inputs[1]
    nameC = inputs[2]
    nameY = outputs[0]

    alpha  = float(attrs.get("alpha", 1.0))
    beta   = float(attrs.get("beta", 1.0))
    transB = int(attrs.get("transB", 0))
    transA = int(not transB)

    if SOFIE.ConvertStringToType(dtype) == SOFIE.ETensorType.FLOAT:
        op = SOFIE.ROperator_Gemm["float"](alpha, beta, transA, transB, nameA, nameB, nameC, nameY)
        return op
    else:
        raise RuntimeError("Unsupported type for Gemm: " + dtype)

# Recurrent operator types
RECURRENT_OPS = {"onnx::RNN", "onnx::LSTM", "onnx::GRU"}

# Helper nodes generated by PyTorch for recurrent models - skip silently
HELPER_NODES = {
    "onnx::Constant", "onnx::Transpose", "onnx::Shape",
    "onnx::Gather", "onnx::Unsqueeze", "onnx::Concat",
    "onnx::Expand", "onnx::Squeeze", "prim::Constant"
}

# Map from ONNX node types to their parsing functions
mapPyTorchNode = {
    "onnx::Gemm":               MakePyTorchGemm,
    "onnx::Elu":                MakePyTorchELU,
    "onnx::MaxPool":            MakePyTorchMaxPool2D,
    "onnx::BatchNormalization": MakePyTorchBatchNorm2D,
    "onnx::RNN":                MakePyTorchRNN,
    "onnx::LSTM":               MakePyTorchLSTM,
}

class PyTorch:

    @staticmethod
    def Parse(filename, input_shapes, input_dtypes=None):
        """
        Parse a PyTorch .pt model file into a SOFIE RModel.

        Parameters:
        filename (str): Path to the .pt model file
        input_shapes (list of list): Shapes of input tensors e.g. [[2, 16]]
        input_dtypes (list of str, optional): Defaults to all 'float'.

        Returns:
        RModel: Parsed SOFIE RModel object
        """
        import torch
        from ROOT.TMVA.Experimental import SOFIE
        from torch.onnx.utils import _model_to_graph

        if not os.path.exists(filename):
            raise RuntimeError("Model file {} not found!".format(filename))

        if input_dtypes is None:
            input_dtypes = ["float"] * len(input_shapes)

        sep = "\\" if os.name == "nt" else "/"
        isep = filename.rfind(sep)
        filename_nodir = filename[isep + 1:] if isep != -1 else filename

        parsetime = time.asctime(time.gmtime(time.time()))
        rmodel = SOFIE.RModel.RModel(filename_nodir, parsetime)

        print("PyTorch Python Parser: parsing model", filename)

        model = torch.jit.load(filename)
        model.cpu()
        model.eval()

        dummy_inputs = [torch.rand(*shape) for shape in input_shapes]
        result  = _model_to_graph(model, dummy_inputs)
        graph   = result[0]
        weights = result[1]

        # Parse operators
        for node in graph.nodes():
            node_type = node.kind()

            # Skip helper nodes generated by PyTorch for recurrent models
            if node_type in HELPER_NODES:
                continue

            attr_names = [x for x in node.attributeNames()]
            node_data = {
                "nodeType":       node_type,
                "nodeAttributes": {k: _node_get(node, k) for k in attr_names},
                "nodeInputs":     [x.debugName() for x in node.inputs()],
                "nodeOutputs":    [x.debugName() for x in node.outputs()],
                "nodeDType":      [x.type().scalarType() for x in node.outputs()],
            }

            parse_fn = mapPyTorchNode.get(node_type)
            if parse_fn is None:
                print(f"  [WARNING] Skipping unsupported node: {node_type}")
                continue

            try:
                # Recurrent ops need raw_node, weights and rmodel
                if node_type in RECURRENT_OPS:
                    input_name = list(graph.inputs())[0].debugName()
                    op = parse_fn(node_data, node, weights, rmodel, input_name)
                else:
                    op = parse_fn(node_data)
                rmodel.AddOperatorReference(op)
                if node_type == "onnx::Gemm":
                    rmodel.AddBlasRoutines({"Gemm", "Gemv"})
            except Exception as e:
                raise RuntimeError(f"TMVA::SOFIE - Failed to parse node {node_type}: {e}")

        # Add weights - skip tensors already registered by recurrent layers
        for name, tensor in weights.items():
            if rmodel.IsInitializedTensor(name):
                continue
            dtype_str = str(tensor.dtype).replace("torch.", "")
            value = tensor.detach().numpy()
            shape = list(value.shape)
            if SOFIE.ConvertStringToType(dtype_str) == SOFIE.ETensorType.FLOAT:
                rmodel.AddInitializedTensor["float"](name, shape, value.flatten())
            else:
                raise TypeError("Unsupported weight type: " + dtype_str)

        # Add input tensor info
        input_names = [list(graph.inputs())[0].debugName()]
        for name, shape, dtype in zip(input_names, input_shapes, input_dtypes):
            sofie_dtype = SOFIE.ConvertStringToType(dtype)
            if sofie_dtype == SOFIE.ETensorType.FLOAT:
                rmodel.AddInputTensorInfo(name, sofie_dtype, shape)
                rmodel.AddInputTensorName(name)
            else:
                raise TypeError("Unsupported input type: " + dtype)

        # Add output tensor names
        # For recurrent models, use the direct RNN/LSTM/GRU node output
        # since helper nodes (Squeeze, Transpose) after it are skipped
        has_recurrent = any(
             node.kind() in RECURRENT_OPS for node in graph.nodes()
        )
        if has_recurrent:
             for node in graph.nodes():
                 if node.kind() in RECURRENT_OPS:
                     output_names = [list(node.outputs())[0].debugName()]
                     break
        else:
            output_names = [x.debugName() for x in graph.outputs()]

        rmodel.AddOutputTensorNameList(output_names)

        return rmodel
